language: node_js
node_js:
  - "8"

before_install:
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++

jobs:
  include:
    - stage: test
      node_js: "8"
      script: npm test && npm run coverage
